/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "gallery.gallery", input: never, result: GalleryResponse } | 
        { key: "games.games", input: never, result: GameResponse } | 
        { key: "messages.messages", input: never, result: MessagesResponse } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export interface Art { id: string, username: string, title: string, art_link: string, artist_link: string | null }

export interface GalleryResponse { count: number, gallery: Array<Art> }

export interface Game { id: string, title: string, game_description: string, game_link: string, git_link: string | null, thumbnail: string | null }

export interface GameResponse { count: number, games: Array<Game> }

export interface Message { id: string, username: string, orig_msg: string, tl_msg: string | null, country: string | null }

export interface MessagesResponse { count: number, messages: Array<Message> }
